import {LoginForm} from '../login-form';
import {RecoverPasswordForm} from '../recover-password-form';
import {ResetPasswordForm} from '../reset-password-form';
import ContactAB from '../contact-ab';
import {BlogAB} from '../blog-ab';
import {publicBlogEntries,publicBlogCounts,publicBlogPost,queryPublicBlog} from '../blog-public';
import ServicesAB from '../services-ab';
import ProjectsAB from '../projects-ab';
import AboutAB from '../about-ab';
import {notFound} from 'next/navigation';
import {ArrowUpRight,ArrowRight,Check,LockKeyhole,ShieldCheck,Code2,Mail,Phone} from 'lucide-react';
import {services,projects,technologies,methodology,posts} from '../content';
import {ProjectGrid,BlogGrid,Newsletter,ContactForm,ShareButton} from '../interactions';
import {requirePortalUser} from '../auth-guard';
import {publicSettings} from '../server';
import {Portal} from '../portal-ui';
import {headers} from "next/headers";
export const dynamic='force-dynamic';
export async function generateMetadata({params}:{params:Promise<{path:string[]}>}){const {path}=await params;const names:Record<string,string>={sobre:'Sobre Agnaldo',projetos:'Portfólio',servicos:'Soluções digitais',blog:'Conteúdo & ideias',contato:'Vamos conversar',entrar:'Área do cliente',portal:'Meu portal',gestao:'Gestão',privacidade:'Privacidade',depoimentos:'Depoimentos',recuperar:'Recuperar senha','redefinir-senha':'Redefinir senha'};const blogPost=path[0]==='blog'&&path[1]?await publicBlogPost(path[1]):null;const detail=path[0]==='projetos'?projects.find(p=>p.slug===path[1])?.name:blogPost?.title;if(blogPost)return {title:blogPost.seoTitle||blogPost.title,description:blogPost.seoDescription||blogPost.summary,keywords:(blogPost.seoKeywords||'').split(',').map(x=>x.trim()).filter(Boolean),alternates:{canonical:'/blog/'+blogPost.slug},openGraph:{type:'article',title:blogPost.seoTitle||blogPost.title,description:blogPost.seoDescription||blogPost.summary,url:'/blog/'+blogPost.slug,images:blogPost.image?[{url:blogPost.image}]:undefined},twitter:{card:'summary_large_image',title:blogPost.seoTitle||blogPost.title,description:blogPost.seoDescription||blogPost.summary,images:blogPost.image?[blogPost.image]:undefined}};if(path[0]==='projetos'&&!path[1])return {title:'Projetos de Web Design | Portfólio Agnaldo Barreto',description:'Explore apresentações de sites, lojas virtuais e soluções digitais. Filtre por categoria e tecnologia e conheça a proposta de cada projeto.'};if(path[0]==='servicos')return {title:'Serviços de Web Design e Desenvolvimento | Agnaldo Barreto',description:'Sites, lojas virtuais, landing pages, portais, consultoria e suporte. Conheça as soluções digitais de Agnaldo Barreto e solicite uma proposta.'};if(path[0]==='blog'&&!path[1])return {title:'Blog de Web Design, WordPress e Estratégia | Agnaldo Barreto',description:'Conteúdos sobre planejamento, design e experiência digital para organizar sua presença na web.'};if(path[0]==='contato')return {title:'Contato e Orçamento | Agnaldo Barreto Web Designer',description:'Solicite orçamento de sites, lojas virtuais, landing pages, portais e soluções digitais. Converse com Agnaldo Barreto sobre seu projeto.'};if(path[0]==='sobre')return {title:'Sobre Agnaldo Barreto | Web Designer',description:'Conheça Agnaldo Barreto: estratégia, design e tecnologia para sites, lojas virtuais e soluções digitais alinhadas ao seu negócio.'};return {title:(detail||names[path[0]]||'Página não encontrada')+' | Agnaldo Barreto'}}
function Intro({label,title,desc}:{label:string,title:React.ReactNode,desc?:string}){return <section className="container page-intro"><a className="breadcrumb" href="/">Início <span>/ {label}</span></a><div className="eyebrow">{label.toUpperCase()}</div><h1>{title}</h1>{desc&&<p>{desc}</p>}</section>}
function CTA(){return <section className="container cta-section"><div className="eyebrow">DA IDEIA À PRÓXIMA ETAPA</div><h2>Vamos construir algo<br/>que faça sentido.</h2><a className="button light" href="/contato">Conte sobre seu projeto <ArrowUpRight size={18}/></a></section>}
export default async function Page({params}:{params:Promise<{path:string[]}>}){const {path}=await params;const page=path[0];if(path.length>2)notFound();if(path.length===2&&!['projetos','blog'].includes(page))notFound();
if(page==='portal'||page==='gestao')return <Protected adminOnly={page==='gestao'}/>;
if(page==='entrar')return <main id="conteudo" className="login-page container"><div className="login-brand"><img src="/logo.png" alt="Agnaldo Barreto — Web Designer"/><h1>Seu projeto.<br/>Nossa conexão.</h1><p>Um espaço para acompanhar cada etapa, consultar solicitações e conversar sobre os próximos passos.</p></div><div className="login-card"><div className="icon-box"><LockKeyhole size={28}/></div><div className="eyebrow">PORTAL DO CLIENTE</div><h2>Bem-vindo de volta.</h2><p>Entre com o e-mail e a senha cadastrados para sua conta.</p><LoginForm/><div className="login-security"><ShieldCheck size={18}/><span>Seu acesso é individual. As informações dos seus projetos ficam disponíveis apenas para você e a administração.</span></div><a className="text-link" href="/contato">Ainda não tem um projeto? Vamos conversar.</a></div></main>;
if(page==='recuperar')return <main id="conteudo" className="login-page container"><div className="login-brand"><img src="/logo.png" alt="Agnaldo Barreto — Web Designer"/><h1>Recupere seu acesso.</h1><p>Informe o e-mail cadastrado para receber as instruções de recuperação.</p></div><div className="login-card"><div className="icon-box"><LockKeyhole size={28}/></div><div className="eyebrow">SEGURANÇA DA CONTA</div><h2>Esqueci minha senha.</h2><RecoverPasswordForm/><a className="text-link" href="/entrar">Voltar ao login</a></div></main>;
if(page==='redefinir-senha')return <main id="conteudo" className="login-page container"><div className="login-brand"><img src="/logo.png" alt="Agnaldo Barreto — Web Designer"/><h1>Defina uma nova senha.</h1><p>Escolha uma senha forte e exclusiva para sua conta.</p></div><div className="login-card"><div className="icon-box"><ShieldCheck size={28}/></div><div className="eyebrow">NOVA SENHA</div><h2>Proteja seu acesso.</h2><ResetPasswordForm/></div></main>;
if(page==='sobre')return <AboutAB/>;
if(page==='servicos')return <ServicesAB/>;
if(page==='projetos'&&!path[1])return <ProjectsAB/>;
if(page==='projetos'){const p=projects.find(p=>p.slug===path[1]);if(!p)notFound();const next=projects[(projects.indexOf(p)+1)%projects.length];return <main id="conteudo" className="ab-case-v64">
<section className="container ab-case-hero-v64">
  <div className="ab-case-copy-v64"><nav className="ab-crumb" aria-label="Localização"><a href="/">Início</a><span>›</span><a href="/projetos">Projetos</a><span>›</span><span aria-current="page">{p.name}</span></nav><div className="ab-case-kicker-v64"><span aria-hidden="true"/><b>CASE · {p.category.toUpperCase()}</b></div><h1>{p.name}</h1><p>{p.short}</p><div className="ab-case-tech-v64">{p.tech.map(t=><span key={t}>{t}</span>)}</div><div className="actions"><a className="button" href="/contato">Conversar sobre um projeto <ArrowRight size={17}/></a><a className="button outline" href="/projetos">Voltar ao portfólio <ArrowRight size={17}/></a></div></div>
  <div className="ab-case-visual-v64"><div className="ab-case-window-v64"><div className="ab-case-window-top-v64"><span/><span/><span/><b>{p.name}</b></div><div className={'ab-case-preview-v64 case-'+p.slug} role="img" aria-label={'Apresentação visual do projeto '+p.name}/></div><div className="ab-case-visual-label-v64"><span>PROJETO SELECIONADO</span><small>DESKTOP · TABLET · MOBILE</small></div></div>
</section>

<section className="container ab-case-meta-v64"><article><small>01 · PROJETO</small><strong>{p.name}</strong></article><article><small>02 · CATEGORIA</small><strong>{p.category}</strong></article><article><small>03 · STACK</small><strong>{p.tech.join(' · ')}</strong></article></section>

<section className="container ab-case-story-v64">
  <article className="ab-case-story-intro-v64"><div className="eyebrow">01 · DESAFIO & OBJETIVO</div><h2>Entender o contexto antes de <em>desenhar a solução.</em></h2><p>{p.brief}</p></article>
  <article className="ab-case-story-panel-v64"><div className="eyebrow">02 · ESTRATÉGIA & DIREÇÃO VISUAL</div><h2>Uma linguagem construída para o projeto.</h2><p>{p.direction}</p><div className="ab-case-scope-v64">{p.scope.map((s,i)=><div key={s}><span>{String(i+1).padStart(2,'0')}</span><Check size={16}/><p>{s}</p></div>)}</div></article>
  <article className="ab-case-responsive-v64"><div><div className="eyebrow">03 · PROCESSO & ENTREGA</div><h2>Uma experiência pensada para <em>diferentes telas.</em></h2><p>A proposta considera hierarquia de conteúdo, desenvolvimento responsivo e revisão das jornadas em desktop, tablet e celular.</p></div><div className="ab-device-grid-v64">{[['Desktop','1440+'],['Tablet','768–1024'],['Mobile','até 767']].map(([label,size],i)=><div key={label}><span>{String(i+1).padStart(2,'0')}</span><Monitor size={24}/><strong>{label}</strong><small>{size}</small></div>)}</div></article>
</section>

<section className="container ab-next-project-v64"><div><small>PRÓXIMO CASE</small><h2>{next.name}</h2><p>{next.category}</p></div><a href={'/projetos/'+next.slug} aria-label={'Ver próximo projeto '+next.name}>Explorar próximo projeto <ArrowRight size={24}/></a></section>
<section className="container ab-case-final-v64"><div><div className="eyebrow">TEM UM PROJETO EM MENTE?</div><h2>Vamos transformar contexto em <em>direção digital.</em></h2><p>Conte o cenário e a necessidade. A conversa inicial ajuda a organizar prioridades antes de definir a solução.</p></div><a className="button" href="/contato">Iniciar uma conversa <ArrowUpRight size={18}/></a><img src="/monograma.png" alt="" aria-hidden="true" loading="lazy"/></section>
</main>}
if(page==='blog'&&!path[1]){const initial=await queryPublicBlog(),entries=await publicBlogEntries(),counts=await publicBlogCounts();return <BlogAB initial={initial} featured={entries.filter(p=>p.featured).slice(0,3).map(({body,...card})=>card)} counts={counts}/>;}
if(page==='blog'){const p=await publicBlogPost(path[1]);if(!p)notFound();const related=(await publicBlogEntries()).filter(x=>x.slug!==p.slug).slice(0,3);const published=p.publishedAt?new Intl.DateTimeFormat('pt-BR',{dateStyle:'long'}).format(new Date(p.publishedAt)):'Conteúdo publicado';const blocks=p.body.trim()?p.body.split(/\n\s*\n/):[p.summary];return <main id="conteudo"><section className="container article-intro"><a className="breadcrumb" href="/blog">Conteúdos <span>/ {p.category}</span></a><div className="eyebrow">{p.category.toUpperCase()}</div><h1>{p.title}</h1><p>{p.summary}</p><div className="article-author"><img src="/monograma.png" alt="AB"/><span>{p.author}<small>{published} · {p.minutes} de leitura</small></span></div></section><article className="article-text">{blocks.map((block,index)=>{const lines=block.split('\n').filter(Boolean);return <section key={index}>{lines.length>1&&<h2>{lines[0]}</h2>}<p>{lines.length>1?lines.slice(1).join(' '):lines[0]}</p></section>})}<ShareButton/></article><section className="container section"><div className="eyebrow">CONTINUE EXPLORANDO</div><h2>Outras ideias para você.</h2><div className="related">{related.map(x=><a className="panel" key={x.slug} href={'/blog/'+x.slug}><small>{x.category}</small><h3>{x.title}</h3><ArrowUpRight/></a>)}</div></section><CTA/></main>}
if(page==='contato')return <ContactAB/>;
if(page==='depoimentos'){const s=await publicSettings();return <main id="conteudo"><Intro label="Depoimentos" title={<>Conexões que fazem<br/><em>parte da história.</em></>}/><section className="container section no-top">{s.testimonials?.length?<div className="values-grid">{s.testimonials.map((t:any,i:number)=><figure className="panel testimonial" key={i}><blockquote>“{t.quote}”</blockquote><figcaption><b>{t.name}</b><p>{t.company} {t.project&&'· '+t.project}</p></figcaption></figure>)}</div>:<div className="empty"><h3>Histórias reais merecem espaço.</h3><p>Os depoimentos serão publicados após autorização e validação dos clientes.</p><a className="button" href="/projetos">Conheça as apresentações <ArrowRight size={17}/></a></div>}</section><CTA/></main>}
if(page==='privacidade')return <main id="conteudo"><Intro label="Privacidade" title="Suas informações, com clareza."/><article className="article-text"><section><h2>Informações enviadas</h2><p>O formulário registra nome, e-mail, telefone, empresa, informações sobre o projeto, origem da solicitação e parâmetros de campanha para análise e atendimento. Um arquivo opcional pode ser armazenado com acesso restrito ao atendimento. A autorização de contato é registrada com data e hora. O cadastro de newsletter registra o e-mail para futuros conteúdos.</p></section><section><h2>Área do cliente</h2><p>O acesso utiliza e-mail e senha por meio do Supabase Auth. As credenciais são tratadas pelo serviço de autenticação e não ficam armazenadas no PostgreSQL operacional do portal. Cookies essenciais mantêm a sessão autenticada e são renovados quando necessário.</p></section><section><h2>Acesso às informações</h2><p>As solicitações e mensagens são armazenadas no servidor. O acesso à área do cliente é individual; a administração pode consultar as informações necessárias para atender os projetos.</p></section><section><h2>Solicitações sobre dados</h2><p>Para solicitar correção, exclusão ou remoção da lista de conteúdos, use o formulário de contato indicando o assunto. O atendimento verificará a identidade do solicitante antes de alterar ou excluir informações pessoais.</p></section><section><h2>Armazenamento local</h2><p>O login pode utilizar cookies necessários à sessão. Este portal não adiciona ferramentas de publicidade ou rastreamento de marketing.</p></section></article></main>;
notFound();}
async function Protected({adminOnly}:{adminOnly:boolean}){const user=await requirePortalUser(adminOnly?'/gestao':'/portal');const operator=user.role==='admin'||user.role==='staff';if(adminOnly&&!operator)return <main id="conteudo" className="container section"><div className="empty"><LockKeyhole size={36}/><h2>Acesso administrativo restrito.</h2><p>Esta conta não possui permissão de gestão.</p><a className="button" href="/portal">Ir para minha área</a></div></main>;return <Portal user={{name:user.displayName,email:user.email}} admin={operator} initialAdmin={adminOnly}/>}
