import {NotebookPortrait} from './notebook-portrait';
import {ArrowRight,Target,Eye,Gem,Check,Monitor,ShoppingCart,PanelsTopLeft,FolderOpen,Code2,Wrench,MessagesSquare,GraduationCap,Search,Lightbulb,Settings,FileText,ShieldCheck,Upload,ChartNoAxesCombined,Users,Compass,Layers,Rocket} from 'lucide-react';
import {technologies} from './content';
import {publicSettings} from './server';
const trajectory=[{title:'Fundamentos',text:'Curiosidade pela tecnologia e atenção à forma como as pessoas usam o digital.',Icon:Compass},{title:'Construção',text:'Design e desenvolvimento conectados à organização do conteúdo.',Icon:Monitor},{title:'Especialização',text:'WordPress, Elementor Pro e Crocoblock na base das soluções.',Icon:Layers},{title:'Integração',text:'Sites, lojas e portais pensados a partir das necessidades do negócio.',Icon:Code2},{title:'Evolução',text:'Aprendizado contínuo e acompanhamento de cada nova etapa.',Icon:Rocket}];
const areas=[{title:'Sites institucionais',text:'Presença digital profissional.',slug:'sites',Icon:Monitor},{title:'Lojas virtuais',text:'Uma jornada de compra clara.',slug:'lojas',Icon:ShoppingCart},{title:'Landing pages',text:'Foco em campanhas e conversão.',slug:'landing',Icon:PanelsTopLeft},{title:'Portfólios',text:'Seu trabalho com contexto.',slug:'portfolios',Icon:FolderOpen},{title:'Portais e sistemas web',text:'Informações e fluxos conectados.',slug:'portais',Icon:Code2},{title:'Manutenção e suporte',text:'Continuidade e evolução do site.',slug:'manutencao',Icon:Wrench},{title:'Consultoria digital',text:'Estratégia para o seu momento.',slug:'consultoria',Icon:MessagesSquare},{title:'Treinamentos e mentoria',text:'Autonomia para sua equipe.',slug:'',Icon:GraduationCap}];
const skills=[['WordPress','Principal'],['Elementor Pro','Principal'],['Crocoblock / JetEngine','Principal'],['WooCommerce','Principal'],['HTML / CSS / JavaScript','Complementar'],['Design UI/UX','Estratégico'],['SEO e performance','Complementar'],['Estratégia digital','Estratégico']];
const steps=[{title:'Descoberta',text:'Entendo seu negócio e suas necessidades.',Icon:Search},{title:'Diagnóstico',text:'Analiso o cenário e as oportunidades.',Icon:Target},{title:'Estratégia',text:'Definimos prioridades e a direção.',Icon:Lightbulb},{title:'Design',text:'Organizo a experiência e a linguagem visual.',Icon:Monitor},{title:'Desenvolvimento',text:'Transformo a proposta em um site funcional.',Icon:Settings},{title:'Conteúdo',text:'Refinamos textos, imagens e organização.',Icon:FileText},{title:'Testes',text:'Reviso navegação, responsividade e funcionamento.',Icon:ShieldCheck},{title:'Publicação',text:'Seu projeto entra no ar com os cuidados finais.',Icon:Upload},{title:'Acompanhamento',text:'Planejamos melhorias e próximos passos.',Icon:ChartNoAxesCombined}];
export default async function AboutAB(){const settings=await publicSettings();return <main id="conteudo" className="ab-about">
<section className="ab-about-hero container"><div className="ab-about-copy"><nav className="ab-crumb" aria-label="Localização"><a href="/">Início</a><span aria-hidden="true">›</span><span aria-current="page">Sobre</span></nav><div className="eyebrow">ESTRATÉGIA · DESIGN · TECNOLOGIA</div><h1>Sobre<br/><em>Agnaldo Barreto</em></h1><p className="ab-lead">Mais que um Web Designer, um parceiro para transformar ideias em resultados.</p><p>Sou Agnaldo Barreto. Crio sites, lojas virtuais e soluções digitais que conectam estratégia, design e tecnologia às necessidades do seu negócio.</p><div className="actions"><a className="button" href="/contato">Vamos conversar <ArrowRight size={18}/></a><a className="button outline" href="/projetos">Meus projetos <ArrowRight size={18}/></a></div></div><div className="ab-about-visual"><img className="ab-hero-globe" src="/digital-globe.png" alt="" aria-hidden="true" width="1254" height="1254"/><div className="ab-network" aria-hidden="true"/><p className="ab-handwritten">Boas ideias<br/>merecem ser<br/>realizadas.</p><NotebookPortrait className="ab-hero-person" src="/agnaldo.png" alt="Agnaldo Barreto sorrindo, sentado à mesa com seu notebook e livros" width="1862" height="845" fetchPriority="high"/><img className="ab-notebook-mark" src="/monograma.png" alt="" aria-hidden="true" width="1254" height="1254"/></div></section>
<section className="container ab-values" aria-label="Missão, visão e valores">{[{title:'Missão',text:'Transformar ideias em soluções digitais que gerem oportunidades e resultados reais.',Icon:Target},{title:'Visão',text:'Ser referência em soluções digitais reconhecidas pela qualidade, inovação e atenção ao negócio.',Icon:Eye},{title:'Valores',text:'',Icon:Gem}].map(({title,text,Icon})=><article className="ab-glass" key={title}><span className="ab-icon"><Icon size={28}/></span><div><h2>{title}</h2>{text?<p>{text}</p>:<ul>{['Ética e transparência','Compromisso com o cliente','Qualidade e inovação','Respeito às pessoas'].map(v=><li key={v}><Check size={16}/>{v}</li>)}</ul>}</div></article>)}</section>
<section className="container ab-section ab-journey" id="trajetoria"><div><div className="eyebrow">MINHA TRAJETÓRIA</div><h2>Uma história de evolução <em>e resultados.</em></h2><p>Meu caminho une aprendizado, prática e interesse por tecnologia. A cada projeto, o ponto de partida é entender as pessoas e o que o negócio precisa comunicar.</p><a href="#perfil" className="button outline">Conheça meu perfil <ArrowRight size={18}/></a></div><ol className="ab-timeline">{trajectory.map(({title,text,Icon},i)=><li key={title}><span className="ab-timeline-icon"><Icon size={24}/></span><small>ETAPA {String(i+1).padStart(2,'0')}</small><h3>{title}</h3><p>{text}</p></li>)}</ol></section>
<section className="ab-profile-band" id="perfil"><div className="container ab-profile"><div className="ab-profile-image"><img className="ab-profile-mark" src="/monograma.png" alt="" aria-hidden="true" width="1254" height="1254" loading="lazy"/><img className="ab-corporate" src="/agnaldo-corporativo.png" alt="Retrato corporativo oficial de Agnaldo Barreto com notebook AB" width="1254" height="1254" loading="lazy"/><span className="ab-photo-caption">AGNALDO BARRETO <span>WEB DESIGNER</span></span></div><div><div className="eyebrow">PERFIL PROFISSIONAL</div><h2>Experiência, estratégia <em>e resultados ao seu lado.</em></h2><p>WordPress, Elementor Pro e Crocoblock fazem parte da minha base de trabalho. Combino essas ferramentas com planejamento e design para criar experiências claras, responsivas e alinhadas ao seu negócio.</p><div className="ab-areas">{areas.map(({title,text,slug,Icon})=><a key={title} href={slug?'/servicos#'+slug:'/contato?servico='+encodeURIComponent(title)}><span className="ab-icon"><Icon size={23}/></span><span><h3>{title}</h3><p>{text}</p></span></a>)}</div></div></div></section>
<section className="container ab-section" id="competencias"><div className="ab-skills ab-glass"><div><div className="eyebrow">COMPETÊNCIAS E HABILIDADES</div><h2>Conhecimento na prática, <em>resultados no digital.</em></h2><p>Tecnologia, visão estratégica e cuidado com a experiência trabalham juntos em cada solução.</p><a className="button" href="/projetos">Ver meus projetos <ArrowRight size={18}/></a></div><div className="ab-skill-grid">{skills.map(([title,level])=><div className="ab-skill" key={title}><div><h3>{title}</h3><span>{level}</span></div><div className={'ab-skill-track level-'+level.toLowerCase()} aria-hidden="true"><span/></div></div>)}<p className="ab-skill-note">Os níveis indicam o papel de cada competência no trabalho, sem pontuações ou percentuais.</p></div></div></section>
<section className="container ab-technologies" id="tecnologias"><div className="eyebrow">TECNOLOGIAS QUE UTILIZO</div><ul>{technologies.map(([name,category])=><li key={name}><Code2 size={24} aria-hidden="true"/><strong>{name}</strong><span>{category}</span></li>)}</ul></section>
<section className="container ab-section" id="metodologia"><div className="ab-process ab-glass"><div><div className="eyebrow">MEU PROCESSO</div><h2>Do planejamento <em>ao resultado.</em></h2><p>Um processo claro, com decisões compartilhadas, para transformar sua ideia em um projeto com direção.</p><a className="button outline" href="/contato">Planejar meu projeto <ArrowRight size={18}/></a></div><ol className="ab-process-grid">{steps.map(({title,text,Icon},i)=><li key={title}><div><Icon size={28}/><span>{String(i+1).padStart(2,'0')}</span></div><h3>{title}</h3><p>{text}</p></li>)}</ol></div></section>
<section className="container ab-authority" aria-label="Diferenciais profissionais"><div className="eyebrow">RESULTADOS QUE GERAM CONFIANÇA</div><div className="ab-proof-grid">{(settings.metricsConfirmed?[{value:settings.projects,label:'Projetos entregues',Icon:FolderOpen},{value:settings.clients,label:'Clientes atendidos',Icon:Users},{value:settings.satisfaction,label:'Satisfação dos clientes',Icon:ShieldCheck},{value:settings.experience,label:'De experiência',Icon:ChartNoAxesCombined}]:[{value:'Estratégia',label:'Decisões com contexto',Icon:Target},{value:'Proximidade',label:'Comunicação ao longo do projeto',Icon:Users},{value:'Qualidade',label:'Cuidado em cada entrega',Icon:ShieldCheck},{value:'Evolução',label:'Visão de continuidade',Icon:ChartNoAxesCombined}]).map(({value,label,Icon})=><div className="ab-glass" key={label}><Icon size={30}/><div><strong>{value||'—'}</strong><p>{label}</p></div></div>)}</div></section>
<section className="ab-final"><div className="container ab-final-inner"><div><div className="eyebrow">VAMOS CONVERSAR?</div><h2>Pronto para transformar sua <em>ideia em realidade?</em></h2></div><div><p>Vamos conversar sobre o seu projeto e encontrar a melhor solução para o seu momento.</p><a className="button" href="/contato">Falar comigo agora <ArrowRight size={18}/></a></div><div className="ab-signoff"><span>Agnaldo<br/>Barreto</span><small>WEB DESIGNER</small><p>IDEIAS QUE GERAM RESULTADOS</p></div></div></section>
</main>}
