export const services = [
{slug:'sites',name:'Sites institucionais',tag:'PRESENÇA & POSICIONAMENTO',desc:'Uma presença digital que explica quem você é, comunica seu valor e facilita o primeiro contato.',problem:'Sua empresa precisa transmitir confiança antes mesmo da primeira conversa.',benefits:['Identidade visual coerente com sua marca','Conteúdo organizado para uma navegação clara','Contato e orçamento a poucos cliques'],features:['Páginas institucionais','Layout responsivo','Formulários de contato','Estrutura básica de SEO'],tech:'WordPress · Elementor Pro · HTML · CSS'},
{slug:'lojas',name:'E-commerce',tag:'COMÉRCIO DIGITAL',desc:'Uma loja virtual pensada para tornar a descoberta de produtos e a compra mais simples.',problem:'Vender online exige uma experiência consistente, do catálogo ao pedido.',benefits:['Catálogo organizado por categorias','Jornada de compra objetiva','Autonomia para administrar produtos'],features:['Catálogo e variações','Carrinho e checkout','Configuração de frete e pagamento conforme o projeto','Gestão de pedidos'],tech:'WordPress · WooCommerce · Elementor'},
{slug:'landing',name:'Landing pages',tag:'CAMPANHAS & CONVERSÃO',desc:'Uma página dedicada a um produto, serviço ou campanha, com uma ação principal bem definida.',problem:'Campanhas perdem força quando o visitante não encontra uma mensagem clara.',benefits:['Mensagem alinhada à campanha','Menos distrações na jornada','Captação de oportunidades'],features:['Estrutura orientada à conversão','Formulário de interesse','Integração de métricas conforme escopo','Versão mobile'],tech:'WordPress · Elementor Pro · JavaScript'},
{slug:'portfolios',name:'Portfólios',tag:'TRABALHO & AUTORIDADE',desc:'Uma seleção de trabalhos apresentada com contexto, personalidade e atenção aos detalhes.',problem:'Bons projetos precisam de uma apresentação que explique suas escolhas.',benefits:['Valorização dos trabalhos','Navegação por categorias','Cases com narrativa'],features:['Galeria de projetos','Páginas individuais','Filtros','Contato'],tech:'WordPress · Elementor · JetEngine'},
{slug:'portais',name:'Portais e sistemas web',tag:'PROCESSOS & OPERAÇÃO',desc:'Informações, pessoas e fluxos de trabalho organizados em uma experiência digital integrada.',problem:'Processos dispersos dificultam o acompanhamento e a tomada de decisão.',benefits:['Informação centralizada','Fluxos adaptados à operação','Visibilidade de status e etapas'],features:['Áreas restritas','Cadastros relacionados','Painéis e filtros','Relatórios definidos no escopo'],tech:'WordPress · Crocoblock · JetEngine · PHP · MySQL'},
{slug:'wordpress',name:'WordPress + Crocoblock',tag:'CONTEÚDO DINÂMICO',desc:'Estruturas de conteúdo conectadas para projetos que vão além de páginas estáticas.',problem:'Cadastros e relacionamentos complexos exigem uma base bem planejada.',benefits:['Conteúdo reutilizável','Relações entre informações','Gestão simplificada'],features:['Tipos de conteúdo','Campos personalizados','Listagens e filtros','Formulários dinâmicos'],tech:'WordPress · Crocoblock · JetEngine'},
{slug:'manutencao',name:'Manutenção',tag:'CONTINUIDADE & EVOLUÇÃO',desc:'Acompanhamento técnico para manter seu site organizado e apoiar sua evolução.',problem:'Um site precisa de cuidados após a publicação.',benefits:['Acompanhamento periódico','Correções priorizadas','Evolução de conteúdo e recursos'],features:['Atualizações planejadas','Revisão de funcionamento','Backups conforme contratação','Suporte com escopo definido'],tech:'WordPress · WooCommerce · Ferramentas de diagnóstico'},
{slug:'consultoria',name:'Consultoria digital',tag:'CLAREZA & DIREÇÃO',desc:'Um olhar estratégico sobre sua presença digital e os próximos passos do seu negócio.',problem:'Nem sempre a solução é criar um site novo; primeiro é preciso entender o cenário.',benefits:['Diagnóstico do momento atual','Priorização de oportunidades','Direção para o investimento'],features:['Conversa de descoberta','Análise da experiência','Recomendações práticas','Plano de evolução'],tech:'Estratégia · UX · Conteúdo · Tecnologia'},{"slug":"treinamentos","name":"Treinamentos e mentoria","tag":"AUTONOMIA & APRENDIZADO","desc":"Orientação prática para você ou sua equipe administrar conteúdo e evoluir no uso das ferramentas digitais.","problem":"Uma boa ferramenta precisa de pessoas preparadas para utilizá-la no dia a dia.","benefits":["Conteúdo alinhado à sua rotina","Aprendizado com aplicações práticas","Mais autonomia para sua equipe"],"features":["WordPress e gestão de conteúdo","Elementor e edição de páginas","Crocoblock conforme o projeto","Orientações e material de apoio"],"tech":"WordPress · Elementor Pro · Crocoblock"}];
export type Project={slug:string,name:string,category:string,short:string,tech:string[],brief:string,direction:string,scope:string[],color:string};
// Cadastre somente projetos reais autorizados, com conteúdo e imagens próprios.
export const projects:Project[]=[];
export const technologies=[['WordPress','CMS','Principal','Criação e gestão de sites, blogs, portais e lojas.'],['Elementor Pro','Construção visual','Principal','Layouts responsivos e sistemas visuais consistentes.'],['Crocoblock','Conteúdo dinâmico','Principal','Listagens, filtros e relações entre cadastros.'],['JetEngine','Modelagem de conteúdo','Principal','Campos personalizados e estruturas de dados.'],['WooCommerce','E-commerce','Principal','Catálogos, produtos e operações de lojas virtuais.'],['HTML5','Estrutura','Complementar','Semântica e organização das páginas.'],['CSS3','Interface','Complementar','Estilos, responsividade e microinterações.'],['JavaScript','Interação','Complementar','Comportamentos e experiências interativas.'],['PHP','Servidor','Complementar','Personalizações no ecossistema WordPress.'],['MySQL','Dados','Complementar','Organização e consulta de dados do projeto.']];
export const methodology=['Descoberta','Diagnóstico','Estratégia','Arquitetura','Design','Desenvolvimento','Conteúdo','Testes','Publicação','Acompanhamento'];
export const posts=[
{slug:'antes-de-criar-seu-site',title:'Antes de criar seu site, responda estas cinco perguntas.',category:'Estratégia',summary:'Objetivo, público, conteúdo, operação e evolução: o ponto de partida de um projeto com direção.',minutes:'4 min',sections:[['Qual é o objetivo principal?','Um site pode apresentar uma empresa, receber contatos ou apoiar vendas. Escolha a ação mais importante para o visitante e organize o conteúdo em torno dela. Objetivos vagos dificultam decisões de arquitetura e design.'],['Quem vai usar o site?','Considere o que seu público procura, o que já conhece e quais dúvidas precisa resolver. A linguagem e a navegação devem partir dessas necessidades, não apenas da organização interna da empresa.'],['Qual conteúdo já existe?','Reúna textos, imagens autorizadas, serviços e informações de contato. Identifique o que precisa ser produzido ou revisado. Um layout não resolve lacunas de conteúdo.'],['Como a operação vai funcionar?','Defina quem recebe os contatos, responde às solicitações e mantém as informações atualizadas. O site precisa estar conectado à rotina do negócio.'],['O que acontece depois da publicação?','Planeje manutenção, acompanhamento e melhorias. A primeira versão é uma base para aprender com o uso real e evoluir com prioridades claras.']]},
{slug:'site-institucional-ou-landing-page',title:'Site institucional ou landing page: qual faz sentido para você?',category:'Design & UX',summary:'Duas estruturas, diferentes objetivos. Entenda como escolher a experiência para o seu momento.',minutes:'3 min',sections:[['Quando apresentar o negócio como um todo','Um site institucional organiza empresa, serviços, projetos e contato em páginas complementares. Faz sentido quando o visitante precisa conhecer diferentes aspectos do negócio antes de conversar.'],['Quando focar em uma única ação','Uma landing page concentra uma oferta ou campanha. O conteúdo deve explicar a proposta, resolver as dúvidas necessárias e levar a uma ação, como solicitar contato.'],['Como tomar a decisão','Comece pelo objetivo e pelo caminho de chegada do visitante. Uma empresa pode usar ambos: o institucional como base de presença e páginas dedicadas para ações específicas. A escolha deve acompanhar a estratégia.']]},
{slug:'conteudo-que-facilita-a-navegacao',title:'Seu conteúdo também faz parte da experiência.',category:'Conteúdo',summary:'Títulos, descrições e rótulos ajudam o visitante a entender o que fazer a seguir.',minutes:'3 min',sections:[['Títulos precisam orientar','Um título deve antecipar o que a pessoa encontrará. Evite expressões genéricas quando uma descrição direta puder ajudar a identificar o conteúdo mais rapidamente.'],['Organize por necessidade','Agrupe informações que respondem à mesma dúvida. Use parágrafos curtos e listas quando houver itens paralelos. Não esconda informações essenciais em blocos difíceis de percorrer.'],['Dê nome às ações','Um botão como “Solicitar orçamento” explica melhor o próximo passo do que um rótulo genérico. Depois de uma ação, confirme o resultado ou informe o que precisa ser corrigido.']]}
];
