import {NotebookPortrait} from './notebook-portrait';
import {ArrowUpRight,ArrowRight,Rocket,ChartNoAxesCombined,ShieldCheck,Monitor,ShoppingCart,PanelsTopLeft,FolderOpen,Code2,Wrench,MessagesSquare,Search,Target,Lightbulb,Settings,FileText,CheckCheck,Upload,Users,Layers,Quote} from 'lucide-react';
import {methodology,posts,technologies,projects} from './content';
import {publicSettings} from './server';
import {redirect} from 'next/navigation';
export const dynamic='force-dynamic';
export default async function Home({searchParams}:{searchParams:Promise<{code?:string}>}){const {code}=await searchParams;if(code)redirect('/redefinir-senha?code='+encodeURIComponent(code));const settings=await publicSettings();const metrics=settings.metricsConfirmed?[settings.projects,settings.clients,settings.satisfaction,settings.experience]:['Estratégia','Parceria','Qualidade','Evolução'];const solutionCards=[[Monitor,'Sites institucionais','sites'],[ShoppingCart,'Lojas virtuais','lojas'],[PanelsTopLeft,'Landing pages','landing'],[FolderOpen,'Portfólios','portfolios'],[Code2,'Portais e sistemas','portais'],[Wrench,'Manutenção e suporte','manutencao'],[MessagesSquare,'Consultoria digital','consultoria']] as const;const homeMethod=methodology.filter(s=>s!=="Arquitetura");const methodIcons=[Search,Target,Lightbulb,Monitor,Settings,FileText,ShieldCheck,Upload,ChartNoAxesCombined];return <main id="conteudo" className="reference-home">
<section className="hero ab-hero-v58 container">
<div className="hero-copy ab-hero-copy-v58">
  <div className="ab-hero-kicker"><span className="ab-status-dot" aria-hidden="true"/><span>WEB DESIGNER · WORDPRESS · EXPERIÊNCIAS DIGITAIS</span></div>
  <h1>Transformo <em>ideias</em> em experiências digitais que geram <em>presença, confiança e resultado.</em></h1>
  <p>Crio sites, lojas, portais e experiências digitais com estratégia, design e tecnologia — conectando marcas a pessoas com clareza, performance e propósito.</p>
  <div className="actions ab-hero-actions"><a className="button ab-primary-cta" href="/projetos">Explorar projetos <ArrowRight size={18}/></a><a className="button outline ab-secondary-cta" href="/contato">Falar sobre meu projeto <MessagesSquare size={17}/></a></div>
  <div className="ab-hero-proof" aria-label="Diferenciais"><div><Rocket size={18}/><span><b>Estratégia</b><small>Experiências com direção</small></span></div><div><Monitor size={18}/><span><b>Design</b><small>Interfaces com propósito</small></span></div><div><ShieldCheck size={18}/><span><b>Performance</b><small>Projetos sólidos e escaláveis</small></span></div></div>
</div>
<div className="hero-visual ab-hero-visual-v58">
  <div className="digital-backdrop ab-hero-globe" aria-hidden="true"/>
  <div className="hero-particles ab-hero-grid" aria-hidden="true"/>
  <div className="ab-hero-halo" aria-hidden="true"/>
  <div className="ab-hero-topline"><span>PORTFÓLIO DIGITAL</span><b>2026</b></div>
  <div className="ab-hero-nameplate"><span>AGNALDO BARRETO</span><small>WEB DESIGNER · DIGITAL EXPERIENCE</small></div>
  <NotebookPortrait className="portrait ab-hero-person-v58" fetchPriority="high" width="1862" height="845" src="/agnaldo.png" alt="Agnaldo Barreto sorrindo em sua mesa com notebook"/>
  <div className="ab-hero-capability"><span><Code2 size={16}/> WordPress</span><span>Elementor Pro</span><span>Crocoblock</span><span>Front-end</span></div>
  <div className="ab-hero-quote-v58">“Design não é só aparência.<br/><em>É direção, experiência e resultado.</em>”</div>
  <div className="ab-hero-corner"><Layers size={19}/><span>Ideias → Estratégia → Design → <b>Resultados</b></span></div>
</div>
</section>
<section className="tech-strip"><div className="container"><div className="eyebrow">TECNOLOGIAS QUE UTILIZO</div><div className="tech-inner">{technologies.map(([name,category])=><a href="/sobre#tecnologias" key={name}><span className="tech-symbol">{name==='WordPress'?'W':name==='Elementor Pro'?'E':name==='WooCommerce'?'WOO':name==='JavaScript'?'JS':name==='Crocoblock'?'C':name==='JetEngine'?'Jet':name==='HTML5'?'5':name==='CSS3'?'3':name==='PHP'?'php':'SQL'}</span><span>{name}</span></a>)}</div></div></section>
<section className="container section home-projects" id="projetos"><div className="section-heading"><div><div className="eyebrow">PROJETOS EM DESTAQUE</div><h2>Sites que geram <em>resultados.</em></h2></div><a className="button outline small" href="/projetos">Ver todos os projetos <ArrowRight size={16}/></a></div><div className="project-grid">{projects.slice(0,3).map(({slug,name,category:cat})=><a className={'project-card project-'+slug} key={slug} href={'/projetos/'+slug}><span className="home-project-image" role="img" aria-label={"Projeto "+name}/><div className="project-info"><h3>{name}</h3><p>{cat}</p><span className="project-cta">Ver projeto <ArrowRight size={14}/></span><ArrowUpRight className="card-arrow" size={18}/></div></a>)}</div>{!projects.length&&<p>Conheça meus serviços e converse sobre a solução ideal para o seu negócio.</p>}<div className="authority-strip">{[[FolderOpen,metrics[0],settings.metricsConfirmed?'Projetos entregues':'Soluções com direção'],[Users,metrics[1],settings.metricsConfirmed?'Clientes atendidos':'Decisões compartilhadas'],[ShieldCheck,metrics[2],settings.metricsConfirmed?'Satisfação dos clientes':'Atenção aos detalhes'],[ChartNoAxesCombined,metrics[3],settings.metricsConfirmed?'De experiência':'Visão de continuidade']].map(([Icon,value,label]:any)=><div key={label}><Icon size={25}/><section><strong>{value||'—'}</strong><span>{label}</span></section></div>)}</div></section>
<section className="container home-about" id="diferenciais"><div className="home-about-copy"><div className="eyebrow">SOBRE AGNALDO BARRETO</div><h2>Paixão por<br/>transformar ideias<br/>em <em>realidade digital.</em></h2><p>Sou Agnaldo Barreto, web designer com foco em WordPress, Elementor Pro e Crocoblock. Ajudo empresas e profissionais a criarem presenças digitais modernas, estratégicas e orientadas a resultados.</p><a className="button small" href="/sobre">Conheça minha história <ArrowRight size={16}/></a></div><div className="home-about-photo corporate-photo"><img src="/agnaldo-corporativo.png" width="1254" height="1254" loading="lazy" alt="Retrato oficial de Agnaldo Barreto com notebook AB em ambiente corporativo azul"/></div><div className="home-differentials">{[[ChartNoAxesCombined,'Estratégia que gera resultados'],[Rocket,'Design com propósito'],[Code2,'Tecnologia a favor do seu negócio'],[Users,'Parceria de longo prazo']].map(([Icon,text]:any)=><div key={text}><Icon size={25}/><span>{text}</span></div>)}</div></section>
<section className="services-section section"><div className="container"><div className="section-heading"><div><div className="eyebrow">MEUS SERVIÇOS</div><h2>Soluções digitais<br/>para o seu negócio.</h2></div><a href="/servicos" className="button outline small">Ver todos os serviços <ArrowRight size={16}/></a></div><div className="compact-services">{solutionCards.map(([Icon,title,slug])=><a href={'/servicos#'+slug} className="service-card" key={slug}><Icon size={27}/><h3>{title}</h3><ArrowUpRight className="card-arrow" size={18}/></a>)}</div></div></section>
<section className="container section process-home"><div><div className="eyebrow">MEU PROCESSO</div><h2>Do planejamento<br/>ao resultado.</h2><p>Um processo claro, com decisões compartilhadas, para transformar sua ideia em um projeto com direção.</p><a className="button small" href="/sobre#metodologia">Saiba como funciona <ArrowRight size={16}/></a></div><div className="process-grid">{homeMethod.map((step,i)=>{const Icon=methodIcons[i];return <div key={step}><small>{String(i+1).padStart(2,'0')}</small><Icon size={29}/><h3>{step}</h3></div>})}</div></section>
<section className="testimonials-home"><div className="container section"><div className="section-heading"><div><div className="eyebrow">DEPOIMENTOS</div><h2>O que dizem<br/>meus clientes.</h2></div><a className="button outline small" href="/depoimentos">Ver depoimentos <ArrowRight size={16}/></a></div>{settings.testimonials?.length?<div className="values-grid">{settings.testimonials.slice(0,3).map((t:any,i:number)=><figure className="panel testimonial" key={i}><Quote size={24}/><blockquote>{t.quote}</blockquote><figcaption><b>{t.name}</b><p>{t.company}</p></figcaption></figure>)}</div>:<div className="testimonial-pending"><Quote size={32}/><div><h3>Histórias reais, conexões de verdade.</h3><p>Conheça meu processo de trabalho e converse sobre as necessidades do seu projeto.</p></div><a className="text-link" href="/projetos">Conheça os projetos <ArrowUpRight size={18}/></a></div>}</div></section>
<section className="container section content-home"><div><div className="eyebrow">CONTEÚDOS</div><h2>Dicas, tutoriais<br/>e estratégias.</h2><p>Conteúdos práticos para planejar e evoluir sua presença digital.</p><a className="button small" href="/blog">Acessar o blog <ArrowRight size={16}/></a></div><div className="home-posts">{posts.map((p,i)=><a className="article-card" key={p.slug} href={'/blog/'+p.slug}><div className={'article-cover cover-'+i}><span>{p.category}</span>{i===0?<Monitor/>:i===1?<PanelsTopLeft/>:<FileText/>}</div><div className="article-body"><h3>{p.title}</h3><small>{p.minutes} de leitura</small><ArrowUpRight size={16}/></div></a>)}</div></section>
<section className="container cta-section final-contact"><div><div className="eyebrow">VAMOS CONVERSAR?</div><h2>Pronto para levar<br/>seu negócio ao<br/><em>próximo nível?</em></h2></div><div><p>Vamos conversar sobre o seu projeto e encontrar a melhor solução para o seu momento.</p><a className="button" href="/contato">Fale comigo agora <ArrowRight size={18}/></a></div><img src="/logo.png" alt="Agnaldo Barreto — Ideias que geram resultados"/></section></main>}
