import {NotebookPortrait} from './notebook-portrait';
import {ArrowUpRight,ArrowRight,Rocket,ChartNoAxesCombined,ShieldCheck,Monitor,ShoppingCart,PanelsTopLeft,FolderOpen,Code2,Wrench,MessagesSquare,Search,Target,Lightbulb,Settings,FileText,CheckCheck,Upload,Users,Layers,Quote} from 'lucide-react';
import {methodology,posts,technologies,projects} from './content';
import {publicSettings} from './server';
import {redirect} from 'next/navigation';
export const dynamic='force-dynamic';
export default async function Home({searchParams}:{searchParams:Promise<{code?:string}>}){const {code}=await searchParams;if(code)redirect('/redefinir-senha?code='+encodeURIComponent(code));const settings=await publicSettings();const metrics=settings.metricsConfirmed?[settings.projects,settings.clients,settings.satisfaction,settings.experience]:['Estratégia','Parceria','Qualidade','Evolução'];const solutionCards=[[Monitor,'Sites institucionais','sites','Presença digital clara, confiável e preparada para apresentar sua marca.'],[ShoppingCart,'Lojas virtuais','lojas','Catálogo, jornada de compra e operação organizados para vender com mais clareza.'],[PanelsTopLeft,'Landing pages','landing','Páginas focadas em campanhas, ofertas e uma ação principal bem definida.'],[FolderOpen,'Portfólios','portfolios','Cases e trabalhos apresentados com contexto, identidade e navegação consistente.'],[Code2,'Portais e sistemas','portais','Áreas restritas, fluxos, cadastros e painéis reunidos em uma experiência integrada.'],[Wrench,'Manutenção e suporte','manutencao','Acompanhamento técnico para manter o projeto estável, atualizado e em evolução.'],[MessagesSquare,'Consultoria digital','consultoria','Diagnóstico e direcionamento para organizar prioridades antes de investir em novas soluções.']] as const;const homeMethod=methodology.filter(s=>s!=="Arquitetura");const methodIcons=[Search,Target,Lightbulb,Monitor,Settings,FileText,ShieldCheck,Upload,ChartNoAxesCombined];return <main id="conteudo" className="reference-home">
<section className="hero ab-hero-v58 container">
<div className="hero-copy ab-hero-copy-v58">
  <div className="ab-hero-kicker"><span className="ab-status-dot" aria-hidden="true"/><span>WEB DESIGNER · WORDPRESS · EXPERIÊNCIAS DIGITAIS</span></div>
  <h1>Transformo <em>ideias</em> em experiências digitais que geram <em>presença, confiança e resultado.</em></h1>
  <p>Crio sites, lojas, portais e experiências digitais com estratégia, design e tecnologia — conectando marcas a pessoas com clareza, performance e propósito.</p>
  <div className="actions ab-hero-actions"><a className="button ab-primary-cta" href="/projetos">Explorar projetos <ArrowRight size={18}/></a><a className="button outline ab-secondary-cta" href="/contato">Falar sobre meu projeto <MessagesSquare size={17}/></a></div>
  <div className="ab-hero-proof" aria-label="Diferenciais"><div><Rocket size={18}/><span><b>Estratégia</b><small>Experiências com direção</small></span></div><div><Monitor size={18}/><span><b>Design</b><small>Interfaces com propósito</small></span></div><div><ShieldCheck size={18}/><span><b>Performance</b><small>Projetos sólidos e escaláveis</small></span></div></div>
</div>
<div className="hero-visual ab-hero-visual-v58">
  <div className="digital-backdrop ab-hero-globe" aria-hidden="true"/>
  <div className="hero-particles ab-hero-grid" aria-hidden="true"/>
  <div className="ab-hero-halo" aria-hidden="true"/>
  <div className="ab-hero-topline"><span>PORTFÓLIO DIGITAL</span><b>2026</b></div>
  <div className="ab-hero-nameplate"><span>AGNALDO BARRETO</span><small>WEB DESIGNER · DIGITAL EXPERIENCE</small></div>
  <NotebookPortrait className="portrait ab-hero-person-v58" fetchPriority="high" width="1862" height="845" src="/agnaldo.png" alt="Agnaldo Barreto sorrindo em sua mesa com notebook"/>
  <div className="ab-hero-capability"><span><Code2 size={16}/> WordPress</span><span>Elementor Pro</span><span>Crocoblock</span><span>Front-end</span></div>
  <div className="ab-hero-quote-v58">“Design não é só aparência.<br/><em>É direção, experiência e resultado.</em>”</div>
  <div className="ab-hero-corner"><Layers size={19}/><span>Ideias → Estratégia → Design → <b>Resultados</b></span></div>
</div>
</section>
<section className="tech-strip ab-stack-v59"><div className="container ab-stack-shell"><div className="ab-stack-heading"><div className="eyebrow">STACK & FERRAMENTAS</div><p>Tecnologias escolhidas conforme a necessidade de cada experiência — da presença institucional à operação de portais e lojas.</p></div><div className="tech-inner ab-stack-grid">{technologies.map(([name,category,tier])=><a className={'ab-tech-card '+(tier==='Principal'?'primary':'')} href="/sobre#tecnologias" key={name}><span className="tech-symbol">{name==='WordPress'?'W':name==='Elementor Pro'?'E':name==='WooCommerce'?'WOO':name==='JavaScript'?'JS':name==='Crocoblock'?'C':name==='JetEngine'?'Jet':name==='HTML5'?'5':name==='CSS3'?'3':name==='PHP'?'php':'SQL'}</span><span className="ab-tech-copy"><b>{name}</b><small>{category}</small></span><span className="ab-tech-tier">{tier}</span></a>)}</div></div></section>
<section className="container section home-projects ab-projects-v59" id="projetos"><div className="section-heading ab-projects-heading"><div><div className="eyebrow">PROJETOS SELECIONADOS</div><h2>Experiências digitais<br/>com <em>estratégia e identidade.</em></h2><p>Cases que combinam posicionamento, arquitetura, design e tecnologia para contextos diferentes de negócio.</p></div><a className="button outline small" href="/projetos">Explorar portfólio <ArrowRight size={16}/></a></div><div className="project-grid ab-project-grid-v59">{projects.slice(0,3).map((p,i)=><a className={'project-card project-'+p.slug+' ab-project-card-v59'} key={p.slug} href={'/projetos/'+p.slug}><div className="ab-project-card-head"><span>{String(i+1).padStart(2,'0')}</span><small>{p.category}</small><ArrowUpRight size={17}/></div><span className="home-project-image" role="img" aria-label={"Projeto "+p.name}/><div className="project-info"><div><h3>{p.name}</h3><p>{p.short}</p></div><div className="ab-project-tech">{p.tech.slice(0,3).map(t=><span key={t}>{t}</span>)}</div><span className="project-cta">Ver case completo <ArrowRight size={14}/></span></div></a>)}</div><div className="authority-strip ab-authority-v59">{[[FolderOpen,metrics[0],settings.metricsConfirmed?'Projetos entregues':'Soluções com direção'],[Users,metrics[1],settings.metricsConfirmed?'Clientes atendidos':'Decisões compartilhadas'],[ShieldCheck,metrics[2],settings.metricsConfirmed?'Satisfação dos clientes':'Atenção aos detalhes'],[ChartNoAxesCombined,metrics[3],settings.metricsConfirmed?'De experiência':'Visão de continuidade']].map(([Icon,value,label]:any)=><div key={label}><Icon size={25}/><section><strong>{value||'—'}</strong><span>{label}</span></section></div>)}</div></section>
<section className="container section ab-about-v60" id="diferenciais"><div className="ab-about-layout-v60"><div className="ab-about-copy-v60"><div className="eyebrow">SOBRE AGNALDO BARRETO</div><h2>Mais do que construir páginas.<br/><em>Eu projeto caminhos digitais com propósito.</em></h2><p>Sou Agnaldo Barreto, web designer focado em transformar necessidades de negócio em experiências digitais claras, funcionais e visualmente consistentes.</p><p>Meu trabalho conecta estratégia, conteúdo, design e tecnologia para que cada projeto tenha direção desde a primeira conversa até a evolução depois da publicação.</p><div className="ab-about-principles-v60"><span>Clareza</span><span>Consistência</span><span>Performance</span><span>Evolução</span></div><a className="button small" href="/sobre">Conheça minha história <ArrowRight size={16}/></a></div><div className="ab-about-visual-v60"><div className="ab-about-glow-v60" aria-hidden="true"/><img className="ab-about-corporate-v60" src="/agnaldo-redesign-oficial.webp" width="560" height="420" loading="lazy" alt="Agnaldo Barreto — composição visual oficial do redesign AB"/><div className="ab-about-tag-v60"><span>WEB DESIGNER</span><small>Estratégia · Design · Tecnologia</small></div><div className="ab-about-signature-v60">Agnaldo Barreto<small>IDEIAS QUE GERAM RESULTADOS</small></div></div></div><div className="ab-differentials-v60">{[[ChartNoAxesCombined,'Estratégia','Decisões guiadas por objetivo, contexto e prioridade.'],[Rocket,'Design com propósito','Interfaces que organizam a informação e fortalecem a presença da marca.'],[Code2,'Tecnologia aplicada','Ferramentas escolhidas de acordo com a necessidade real do projeto.'],[Users,'Parceria contínua','Construção colaborativa, comunicação clara e visão de evolução.']].map(([Icon,title,text]:any,i:number)=><article key={title}><span className="ab-diff-number">{String(i+1).padStart(2,'0')}</span><Icon size={24}/><div><h3>{title}</h3><p>{text}</p></div></article>)}</div></section>
<section className="services-section section ab-services-v60"><div className="container"><div className="section-heading ab-services-heading-v60"><div><div className="eyebrow">SOLUÇÕES DIGITAIS</div><h2>Serviços que acompanham<br/><em>o momento do seu negócio.</em></h2><p>Da presença institucional a portais e operações mais complexas, cada solução parte do problema que precisa ser resolvido.</p></div><a href="/servicos" className="button outline small">Ver todos os serviços <ArrowRight size={16}/></a></div><div className="ab-services-grid-v60">{solutionCards.map(([Icon,title,slug,desc],i)=><a href={'/servicos#'+slug} className={'service-card ab-service-card-v60 service-'+slug} key={slug}><div className="ab-service-card-top"><span>{String(i+1).padStart(2,'0')}</span><ArrowUpRight size={17}/></div><Icon className="ab-service-icon-v60" size={28}/><h3>{title}</h3><p>{desc}</p><span className="ab-service-link-v60">Conhecer solução <ArrowRight size={14}/></span></a>)}</div></div></section>
<section className="container section process-home ab-process-v61"><div className="ab-process-heading-v61"><div><div className="eyebrow">PROCESSO DE TRABALHO</div><h2>Da primeira conversa<br/><em>à evolução do projeto.</em></h2></div><div><p>Um fluxo claro reduz ruído, organiza decisões e mantém cada etapa conectada ao objetivo do projeto.</p><a className="button outline small" href="/sobre#metodologia">Conhecer metodologia <ArrowRight size={16}/></a></div></div><div className="ab-process-phases-v61" aria-hidden="true"><span>01 · Entender</span><span>02 · Direcionar</span><span>03 · Construir</span><span>04 · Entregar & evoluir</span></div><div className="process-grid ab-process-grid-v61">{homeMethod.map((step,i)=>{const Icon=methodIcons[i];const phase=i<2?'Descoberta':i<4?'Direção':i<7?'Construção':'Entrega';return <article key={step}><div className="ab-process-card-top"><small>{String(i+1).padStart(2,'0')}</small><span>{phase}</span></div><Icon size={27}/><h3>{step}</h3><span className="ab-process-line" aria-hidden="true"/></article>})}</div></section>
<section className="testimonials-home ab-testimonials-v61"><div className="container section"><div className="section-heading ab-testimonials-heading-v61"><div><div className="eyebrow">DEPOIMENTOS</div><h2>Projetos são feitos de<br/><em>processo, confiança e parceria.</em></h2><p>Relatos são publicados somente quando houver autorização e validação do cliente.</p></div><a className="button outline small" href="/depoimentos">Ver depoimentos <ArrowRight size={16}/></a></div>{settings.testimonials?.length?<div className="values-grid ab-testimonial-grid-v61">{settings.testimonials.slice(0,3).map((t:any,i:number)=><figure className="panel testimonial ab-testimonial-card-v61" key={i}><div className="ab-quote-mark-v61"><Quote size={21}/><span>{String(i+1).padStart(2,'0')}</span></div><blockquote>{t.quote}</blockquote><figcaption><b>{t.name}</b><p>{t.company}{t.project?' · '+t.project:''}</p></figcaption></figure>)}</div>:<div className="testimonial-pending ab-testimonial-empty-v61"><div className="ab-empty-quote-v61"><Quote size={34}/></div><div><small>TRANSPARÊNCIA PRIMEIRO</small><h3>Depoimentos reais, publicados no momento certo.</h3><p>Enquanto os relatos autorizados não estão publicados, você pode conhecer os cases, o processo e a forma de trabalho diretamente no portfólio.</p></div><a className="button outline small" href="/projetos">Explorar cases <ArrowRight size={16}/></a></div>}</div></section>
<section className="container section content-home ab-content-v61"><div className="ab-content-heading-v61"><div className="eyebrow">CONTEÚDOS & IDEIAS</div><h2>Estratégia, design e tecnologia<br/><em>explicados de forma prática.</em></h2><p>Conteúdos para ajudar você a tomar decisões melhores sobre presença digital, experiência e evolução do seu projeto.</p><a className="button outline small" href="/blog">Acessar todos os conteúdos <ArrowRight size={16}/></a></div><div className="ab-content-layout-v61">{posts[0]&&<a className="article-card ab-featured-post-v61" href={'/blog/'+posts[0].slug}><div className="article-cover cover-0"><span>{posts[0].category}</span><Monitor/></div><div className="article-body"><small>EM DESTAQUE · {posts[0].minutes} DE LEITURA</small><h3>{posts[0].title}</h3><p>{posts[0].summary}</p><span>Continuar lendo <ArrowRight size={15}/></span></div></a>}<div className="ab-content-stack-v61">{posts.slice(1).map((p,i)=><a className="article-card ab-post-row-v61" key={p.slug} href={'/blog/'+p.slug}><div className={'article-cover cover-'+(i+1)}>{i===0?<PanelsTopLeft/>:<FileText/>}</div><div className="article-body"><small>{p.category} · {p.minutes}</small><h3>{p.title}</h3><span>Ver conteúdo <ArrowUpRight size={15}/></span></div></a>)}</div></div></section>
<section className="container ab-final-cta-v62"><div className="ab-final-cta-glow" aria-hidden="true"/><div className="ab-final-cta-mark"><img src="/monograma.png" width="1254" height="1254" loading="lazy" alt="" aria-hidden="true"/></div><div className="ab-final-cta-copy"><div className="eyebrow">PRÓXIMO PROJETO</div><h2>Tem uma ideia, um desafio<br/>ou algo que precisa <em>evoluir?</em></h2><p>Vamos entender o seu momento, organizar prioridades e transformar a necessidade em uma experiência digital com direção.</p></div><div className="ab-final-cta-actions"><a className="button" href="/contato">Conversar sobre meu projeto <ArrowRight size={18}/></a><a className="button outline" href="/projetos">Explorar os cases <ArrowUpRight size={17}/></a><small>Estratégia · Design · Tecnologia · Evolução</small></div></section></main>}
