import {NotebookPortrait} from './notebook-portrait';
import {ArrowRight,Monitor,ShoppingCart,PanelsTopLeft,FolderOpen,Database,Wrench,ChartNoAxesCombined,GraduationCap,Target,PenTool,Code2,Check,Search,Lightbulb,Settings,FileText,ShieldCheck,Upload,Quote,Users} from 'lucide-react';
import {serviceCatalog,serviceSteps} from './services-data';
import {ServicesFAQ,ServiceMore} from './services-faq';
import {publicSettings} from './server';
const icons=[Monitor,ShoppingCart,PanelsTopLeft,FolderOpen,Database,Wrench,ChartNoAxesCombined,GraduationCap];
const stepIcons=[Search,Target,Lightbulb,PenTool,Settings,FileText,ShieldCheck,Upload,ChartNoAxesCombined];
export default async function ServicesAB(){const settings=await publicSettings();const testimonials=(settings.testimonials||[]).slice(0,3);return <main id="conteudo" className="ab-services-page"><section className="container ab-services-hero"><div className="ab-services-copy"><nav className="ab-crumb" aria-label="Localização"><a href="/">Início</a><span aria-hidden="true">›</span><span aria-current="page">Serviços</span></nav><div className="eyebrow">SOLUÇÕES DIGITAIS</div><h1>Transformando<br/>ideias em<br/><em>resultados.</em></h1><p>Soluções digitais personalizadas para fortalecer sua marca, aproximar clientes e apoiar o crescimento do seu negócio.</p><div className="actions"><a className="button" href="/contato">Solicitar orçamento <ArrowRight size={18}/></a><a className="button outline" href="#processo">Conheça meu processo <ArrowRight size={18}/></a></div></div><div className="ab-services-visual"><img className="ab-services-globe" src="/digital-globe.png" width="1254" height="1254" alt="" aria-hidden="true"/><div className="ab-services-network" aria-hidden="true"/><NotebookPortrait className="ab-services-person" src="/agnaldo.png" width="1862" height="845" alt="Agnaldo Barreto sorrindo, sentado atrás do notebook em sua mesa de trabalho" fetchPriority="high"/><img className="ab-services-mark" src="/monograma.png" width="1254" height="1254" alt="" aria-hidden="true"/><p className="ab-services-quote">Mais que sites,<br/>conectamos pessoas<br/>a oportunidades.</p><ul className="ab-services-principles">{[[Target,'Estratégia'],[PenTool,'Design'],[Code2,'Tecnologia'],[ChartNoAxesCombined,'Resultados']].map(([Icon,title]:any)=><li key={title}><Icon size={21}/>{title}</li>)}</ul></div></section>
<section className="container ab-services-section" id="solucoes"><div className="ab-services-heading"><div><div className="eyebrow">MEUS SERVIÇOS</div><h2>Soluções digitais<br/>para o <em>seu negócio.</em></h2></div><p>Do site institucional à loja virtual, combino WordPress, Elementor Pro e Crocoblock com planejamento e design para construir a solução adequada ao seu momento.</p></div><div className="ab-services-grid">{serviceCatalog.map((s,i)=>{const Icon=icons[i];return <article className="ab-service-tile" key={s.slug} id={s.slug}>{s.slug==='portais'&&<span id="wordpress"/>}<div className={'ab-service-image image-'+i}><img src={s.image} alt={'Ilustração de '+s.title+' no modelo visual fornecido'} width="822" height="1914" loading="lazy" decoding="async"/></div><div className="ab-service-tile-body"><div className="ab-service-title"><Icon size={28}/><h3>{s.title}</h3></div><p>{s.desc}</p><ul className="ab-service-checks">{s.benefits.map(b=><li key={b}><Check size={15}/><span>{b}</span></li>)}</ul><ServiceMore title={s.title} problem={s.problem} features={s.features} tech={s.tech} quoteUrl={s.quoteUrl}/></div></article>})}</div></section>
<section className="container ab-services-section" id="processo"><div className="ab-services-process ab-service-panel"><div><div className="eyebrow">MEU PROCESSO</div><h2>Do planejamento <em>ao resultado.</em></h2><p>Um processo claro, com decisões compartilhadas, para transformar sua ideia em um projeto com direção.</p><a className="button outline" href="/contato">Planejar meu projeto <ArrowRight size={18}/></a></div><ol>{serviceSteps.map(([title,text],i)=>{const Icon=stepIcons[i];return <li key={title}><div><Icon size={26}/><span>{String(i+1).padStart(2,'0')}</span></div><h3>{title}</h3><p>{text}</p></li>})}</ol></div></section>
<section className="ab-services-why"><div className="container"><div><div className="eyebrow">POR QUE ESCOLHER</div><h2>Por que escolher <em>meus serviços?</em></h2><ul>{['Atendimento personalizado','Planejamento antes do desenvolvimento','Tecnologia alinhada ao seu negócio','Foco na experiência e nos objetivos'].map(b=><li key={b}><Check size={19}/>{b}</li>)}</ul></div><div className="ab-services-why-photo"><img className="ab-services-why-mark" src="/monograma.png" alt="" aria-hidden="true" width="1254" height="1254" loading="lazy"/><img className="ab-services-corporate" src="/agnaldo-corporativo.png" alt="Retrato corporativo oficial de Agnaldo Barreto com notebook AB" width="1254" height="1254" loading="lazy"/></div><div className="ab-services-conversation"><h3>Vamos conversar sobre o seu projeto?</h3><p>Conte suas necessidades. Vamos avaliar as possibilidades e definir os próximos passos com clareza.</p><a className="button" href="/contato">Falar comigo agora <ArrowRight size={18}/></a><p className="ab-services-signature">Seu sucesso também<br/>é o meu resultado.<span>Agnaldo Barreto</span></p></div></div></section>
<section className="container ab-services-section" id="depoimentos"><div className="ab-services-heading"><div><div className="eyebrow">DEPOIMENTOS</div><h2>O que dizem<br/><em>meus clientes.</em></h2></div><a className="button outline" href="/depoimentos">Ver depoimentos <ArrowRight size={18}/></a></div>{testimonials.length?<div className="ab-services-testimonials">{testimonials.map((t:any,i:number)=><figure className="ab-service-panel" key={i}><Quote size={28} aria-hidden="true"/><blockquote>{t.quote}</blockquote><figcaption><span className="ab-testimonial-avatar" aria-hidden="true">{t.name?.slice(0,1)}</span><span><strong>{t.name}</strong><small>{t.company}</small></span></figcaption></figure>)}</div>:<div className="ab-service-panel ab-services-testimonial-empty"><Users size={32}/><div><h3>Histórias reais merecem espaço.</h3><p>Os depoimentos serão apresentados após autorização e validação dos clientes.</p></div><a className="text-link" href="/projetos">Conheça os projetos <ArrowRight size={18}/></a></div>}</section>
<section className="container ab-services-section ab-services-faq" id="perguntas"><div><div className="eyebrow">DÚVIDAS FREQUENTES</div><h2>Perguntas<br/><em>mais comuns.</em></h2><p>Tire suas dúvidas sobre o processo, a contratação e o acompanhamento.</p></div><ServicesFAQ/><aside className="ab-service-panel ab-services-mini-cta"><img src="/logo.png" alt="Agnaldo Barreto — Web Designer. Ideias que geram resultados" width="1536" height="1024" loading="lazy"/><a className="button" href="/contato">Solicitar orçamento <ArrowRight size={17}/></a></aside></section></main>}
