import {readJsonObject,failure} from '../../request-security';
import {rateLimit,requestSubject} from '../../rate-limit';
import {identity,rawDb,error,sameOrigin,textValue} from '../../server';
export async function GET(){const {user,admin}=await identity();if(!user)return error('Entre para acessar sua área.',401);try{const db=rawDb();const leads=admin?await db.prepare('SELECT * FROM leads ORDER BY created DESC LIMIT 500').all():await db.prepare('SELECT * FROM leads WHERE user_id = ? ORDER BY created DESC LIMIT 100').bind(user.userId).all();const projects=admin?await db.prepare('SELECT * FROM client_projects ORDER BY created DESC LIMIT 500').all():await db.prepare('SELECT * FROM client_projects WHERE user_id = ? ORDER BY created DESC LIMIT 100').bind(user.userId).all();const messages=admin?await db.prepare('SELECT * FROM messages ORDER BY created DESC LIMIT 1000').all():await db.prepare('SELECT m.* FROM messages m JOIN client_projects p ON p.id=m.project_id WHERE p.user_id = ? ORDER BY m.created DESC LIMIT 500').bind(user.userId).all();const clients=admin?await db.prepare('SELECT * FROM crm_clients ORDER BY updated DESC LIMIT 500').all():{results:[]};return Response.json({leads:leads.results,projects:projects.results,messages:messages.results,clients:clients.results,admin},{headers:{'Cache-Control':'private, no-store'}})}catch(e){return failure(e,'portal GET')}}
export async function POST(req:Request){const {user,admin}=await identity();if(!user)return error('Entre para continuar.',401);if(!sameOrigin(req))return error('Origem não permitida.',403);try{await rateLimit('portal',user.userId,30,60000);const b = await readJsonObject(req) as Record<string, any>; if (!b || typeof b !== "object" || Array.isArray(b)) return error("Dados inválidos.");const db=rawDb();
if(b.action==='message'){const project=await db.prepare('SELECT id,user_id FROM client_projects WHERE id = ?').bind(textValue(b.projectId,40)).first<{id:string,user_id:string}>();if(!project||(!admin&&project.user_id!==user.userId))return error('Projeto não encontrado.',404);const body=textValue(b.body,4000);if(!body)return error('Escreva uma mensagem.');await rateLimit('message',user.userId,10,60000);const id=crypto.randomUUID();await db.prepare('INSERT INTO messages (id,project_id,user_id,author,body,created) VALUES (?,?,?,?,?,?)').bind(id,project.id,user.userId,admin?'Agnaldo Barreto':user.displayName,body,Date.now()).run();return Response.json({id});}
if(!admin)return error('Acesso administrativo necessário.',403);
if(b.action==='lead-status'){if(!['Recebido','Em análise','Proposta enviada','Aprovado','Concluído','Arquivado'].includes(b.status))return error('Status inválido.');const r=await db.prepare('UPDATE leads SET status = ? WHERE id = ?').bind(b.status,textValue(b.id,40)).run();return r.meta.changes?Response.json({ok:true}):error('Solicitação não encontrada.',404);}
if(b.action==='convert-client'){const lead=await db.prepare('SELECT * FROM leads WHERE id = ?').bind(textValue(b.leadId,40)).first<Record<string,any>>();if(!lead)return error('Solicitação não encontrada.',404);const existing=await db.prepare('SELECT id FROM crm_clients WHERE lower(email)=lower(?)').bind(lead.email).first<{id:string}>();if(existing)return Response.json({id:existing.id,existing:true});const id=crypto.randomUUID();const now=Date.now();await db.prepare('INSERT INTO crm_clients (id,lead_id,user_id,name,email,phone,company,status,notes,created,updated) VALUES (?,?,?,?,?,?,?,?,?,?,?)').bind(id,lead.id,lead.user_id,lead.name,lead.email,lead.phone,lead.company,'Ativo','Convertido a partir do CRM',now,now).run();await db.prepare('UPDATE leads SET status = ? WHERE id = ?').bind('Aprovado',lead.id).run();return Response.json({id});}
if(b.action==='create-project'){const lead=await db.prepare('SELECT id,user_id FROM leads WHERE id = ?').bind(textValue(b.leadId,40)).first<{id:string,user_id:string|null}>();if(!lead)return error('Selecione uma solicitação válida.');const name=textValue(b.name,150);if(!name)return error('Informe o nome do projeto.');const id=crypto.randomUUID();await db.prepare('INSERT INTO client_projects (id,lead_id,user_id,name,phase,progress,deadline,description,created) VALUES (?,?,?,?,?,?,?,?,?)').bind(id,lead.id,lead.user_id,name,'Descoberta',0,textValue(b.deadline,100),textValue(b.description,2000),Date.now()).run();return Response.json({id});}
if(b.action==='update-project'){const phases=['Descoberta','Diagnóstico','Estratégia','Arquitetura','Design','Desenvolvimento','Conteúdo','Testes','Publicação','Acompanhamento'];const progress=typeof b.progress==='number'?b.progress:typeof b.progress==='string'&&/^(0|[1-9][0-9]?|100)$/.test(b.progress)?Number(b.progress):NaN;if(!phases.includes(b.phase)||!Number.isInteger(progress)||progress<0||progress>100)return error('Etapa ou progresso inválido.');const r=await db.prepare('UPDATE client_projects SET phase = ?,progress = ?,deadline = ?,description = ? WHERE id = ?').bind(b.phase,progress,textValue(b.deadline,100),textValue(b.description,2000),textValue(b.id,40)).run();return r.meta.changes?Response.json({ok:true}):error('Projeto não encontrado.',404);}
return error('Ação não reconhecida.');}catch(e){return failure(e,'portal POST')}}
